[package]
name = "prac"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
serde = {version = "1.0.149", features = ["derive"]}
serde_json = "1.0.149"

clap = {version = "4.5.58", features = ["derive"]}
chrono = "0.4.43"
